runtime: nodejs22
env: standard

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  AZURE_FUNCTION_URL: "https://simplefinance.azurewebsites.net"
  HOST_KEY: "jHMTQt3HujrD95gb7i8X1p5ovrH-yzStfSeLDHPLMiEnAzFuy3B_jQ=="
